version: "3.8"

services:
  power-button-app:
    container_name: power-button-app
    image: ghcr.io/walzen-group/raspmi:main
    ports:
      - "80:5000"
    environment:
      - TELEGRAM_TOKEN=your_telegram_token
      - TELEGRAM_CHAT_ID=your_telegram_chat_id
    privileged: true
    restart: always
